package gdbplugin;

import java.util.Map;

public class ButtonsData {

    // Map of method name to parameter names, used for dynamic generation of input
    // fields for commands

    public static final Map<String, String[]> PARAM_NAME_MAP = Map.ofEntries(
            Map.entry("startEverything", new String[] { "program", "port" }),
            Map.entry("startGdbServer", new String[] { "program", "port" }),
            Map.entry("startGdb", new String[] {}),
            Map.entry("connectToServer", new String[] { "port", "programPath" }),
            Map.entry("setBreakpoint",
                    new String[] { "location", "temporary", "hardware", "disabled", "condition",
                            "ignoreCount" }),
            Map.entry("listBreakpoints", new String[] {}),
            Map.entry("deleteBreakpoints", new String[] { "numbers" }),
            Map.entry("disableBreakpoints", new String[] { "numbers" }),
            Map.entry("enableBreakpoints", new String[] { "numbers" }),
            Map.entry("breakpointInfo", new String[] { "number" }),
            Map.entry("breakAfter", new String[] { "breakpointNumber", "count" }),
            Map.entry("setBreakpointCondition", new String[] { "breakpointNumber", "condition" }),
            Map.entry("setBreakpointConditionForced", new String[] { "breakpointNumber", "condition" }),
            Map.entry("setBreakpointCommands", new String[] { "breakpointNumber", "commands" }),
            Map.entry("dprintf", new String[] { "location", "format", "args" }),
            Map.entry("watch", new String[] { "expression", "type" }),
            Map.entry("setTracepointPasscount", new String[] { "tracepointNumber", "passcount" }),
            Map.entry("setProgramArguments", new String[] { "args" }),
            Map.entry("changeDirectory", new String[] { "path" }),
            Map.entry("environmentDirectory", new String[] { "action", "paths" }),
            Map.entry("resetSourceDirectories", new String[] {}),
            Map.entry("resetAndAddSourceDirectories", new String[] { "paths" }),
            Map.entry("showSourceDirectories", new String[] {}),
            Map.entry("environmentPath", new String[] { "action", "paths" }),
            Map.entry("showEnvironmentPath", new String[] {}),
            Map.entry("addEnvironmentPath", new String[] { "paths" }),
            Map.entry("resetEnvironmentPath", new String[] {}),
            Map.entry("resetAndAddEnvironmentPath", new String[] { "paths" }),
            Map.entry("printWorkingDirectory", new String[] {}),
            Map.entry("threadInfo", new String[] { "threadId" }),
            Map.entry("listThreadIds", new String[] {}),
            Map.entry("selectThread", new String[] { "threadId" }),
            Map.entry("adaTaskInfo", new String[] { "taskId" }),
            Map.entry("run", new String[] { "groupId", "startAtMain", "all" }),
            Map.entry("runAndStopAtMain", new String[] {}),
            Map.entry("runAll", new String[] {}),
            Map.entry("runThreadGroup", new String[] { "groupId" }),
            Map.entry("continueExec", new String[] { "groupId", "reverse", "all" }),
            Map.entry("continueThreadGroup", new String[] { "groupId" }),
            Map.entry("continueAll", new String[] {}),
            Map.entry("continueReverse", new String[] {}),
            Map.entry("interrupt", new String[] { "groupId", "all" }),
            Map.entry("interruptAll", new String[] {}),
            Map.entry("interruptThreadGroup", new String[] { "groupId" }),
            Map.entry("next", new String[] { "reverse" }),
            Map.entry("nextReverse", new String[] {}),
            Map.entry("step", new String[] { "reverse" }),
            Map.entry("stepReverse", new String[] {}),
            Map.entry("until", new String[] { "location" }),
            Map.entry("nextInstruction", new String[] { "reverse" }),
            Map.entry("nextInstructionReverse", new String[] {}),
            Map.entry("stepInstruction", new String[] { "reverse" }),
            Map.entry("stepInstructionReverse", new String[] {}),
            Map.entry("finish", new String[] { "reverse" }),
            Map.entry("finishReverse", new String[] {}),
            Map.entry("returnFromFunction", new String[] {}),
            Map.entry("jump", new String[] { "location" }),
            Map.entry("enableFrameFilters", new String[] {}),
            Map.entry("stackInfoFrame", new String[] {}),
            Map.entry("stackInfoDepth", new String[] { "maxDepth" }),
            Map.entry("stackListFrames", new String[] { "low", "high", "noFrameFilters" }),
            Map.entry("stackListArguments", new String[] { "printValues", "low", "high" }),
            Map.entry("stackListLocals",
                    new String[] { "noFrameFilters", "skipUnavailable", "printValues" }),
            Map.entry("stackListVariables",
                    new String[] { "noFrameFilters", "skipUnavailable", "threadId", "frame",
                            "printValues" }),
            Map.entry("selectFrame", new String[] { "frameNumber" }),
            Map.entry("enablePrettyPrinting", new String[] {}),
            Map.entry("varCreate", new String[] { "expression", "floating" }),
            Map.entry("varDelete", new String[] { "name", "childrenOnly" }),
            Map.entry("varSetFormat", new String[] { "name", "format" }),
            Map.entry("varShowFormat", new String[] { "name" }),
            Map.entry("varInfoNumChildren", new String[] { "name" }),
            Map.entry("varListChildren", new String[] { "name", "from", "to" }),
            Map.entry("varInfoType", new String[] { "name" }),
            Map.entry("varInfoExpression", new String[] { "name" }),
            Map.entry("varInfoPathExpression", new String[] { "name" }),
            Map.entry("varShowAttributes", new String[] { "name" }),
            Map.entry("varEvaluate", new String[] { "name", "format" }),
            Map.entry("varAssign", new String[] { "name", "value" }),
            Map.entry("varUpdateAll", new String[] {}),
            Map.entry("varUpdate", new String[] { "name" }),
            Map.entry("varSetFrozen", new String[] { "name", "frozen" }),
            Map.entry("varSetUpdateRange", new String[] { "name", "from", "to" }),
            Map.entry("varSetVisualizer", new String[] { "name", "visualizer" }),
            Map.entry("dataDisassembleRange", new String[] { "start", "end" }),
            Map.entry("dataDisassembleFunction", new String[] { "function" }),
            Map.entry("dataDisassembleFileLine", new String[] { "file", "line" }),
            Map.entry("dataDisassembleFileLineCount", new String[] { "file", "line", "count" }),
            Map.entry("dataDisassembleWithOpcodes", new String[] { "start", "end" }),
            Map.entry("dataDisassembleWithSource", new String[] { "start", "end" }),
            Map.entry("dataEvaluateExpression", new String[] { "expr" }),
            Map.entry("dataListChangedRegisters", new String[] {}),
            Map.entry("dataListRegisterNames", new String[] { "regs" }),
            Map.entry("dataListRegisterValues", new String[] { "format", "regs" }),
            Map.entry("dataReadMemoryBytes", new String[] { "address", "count" }),
            Map.entry("dataReadMemoryBytesOffset", new String[] { "address", "offset", "count" }),
            Map.entry("dataWriteMemoryBytes", new String[] { "address", "hexBytes", "count" }),
            Map.entry("traceFindNone", new String[] {}),
            Map.entry("traceFindFrameNumber", new String[] { "frame" }),
            Map.entry("traceFindTracepointNumber", new String[] { "tp" }),
            Map.entry("traceFindPc", new String[] { "address" }),
            Map.entry("traceFindPcInsideRange", new String[] { "start", "end" }),
            Map.entry("traceFindPcOutsideRange", new String[] { "start", "end" }),
            Map.entry("traceFindLine", new String[] { "location" }),
            Map.entry("traceDefineVariable", new String[] { "name", "value" }),
            Map.entry("traceListVariables", new String[] {}),
            Map.entry("traceFrameCollected", new String[] {}),
            Map.entry("traceFrameCollectedVarPrint", new String[] { "mode" }),
            Map.entry("traceFrameCollectedCompPrint", new String[] { "mode" }),
            Map.entry("traceFrameCollectedRegisters", new String[] { "format" }),
            Map.entry("traceFrameCollectedMemoryContents", new String[] {}),
            Map.entry("traceFrameCollectedFull", new String[] { "varMode", "compMode", "regFormat" }),
            Map.entry("traceStart", new String[] {}),
            Map.entry("traceStop", new String[] {}),
            Map.entry("traceStatus", new String[] {}),
            Map.entry("traceSave", new String[] { "filename", "remote", "ctf" }),
            Map.entry("symbolInfoFunctions",
                    new String[] { "nameRegex", "typeRegex", "limit", "includeNonDebug" }),
            Map.entry("symbolInfoModuleFunctions", new String[] { "module", "name", "type" }),
            Map.entry("symbolInfoModuleVariables", new String[] { "module", "name", "type" }),
            Map.entry("symbolInfoModules", new String[] { "name", "limit" }),
            Map.entry("symbolInfoTypes", new String[] { "name", "limit" }),
            Map.entry("symbolInfoVariables",
                    new String[] { "name", "type", "limit", "includeNonDebug" }),
            Map.entry("symbolListLines", new String[] { "filename" }),
            Map.entry("fileExecAndSymbols", new String[] { "file" }),
            Map.entry("fileExecFile", new String[] { "file" }),
            Map.entry("fileListExecSourceFile", new String[] {}),
            Map.entry("fileListExecSourceFiles", new String[] { "regexp" }),
            Map.entry("fileListSharedLibraries", new String[] { "regexp" }),
            Map.entry("fileSymbolFile", new String[] { "file" }),
            Map.entry("targetAttach", new String[] { "pidOrGidOrFile" }),
            Map.entry("targetDetach", new String[] { "pidOrGid" }),
            Map.entry("targetDisconnect", new String[] {}),
            Map.entry("targetDownload", new String[] {}),
            Map.entry("targetFlashErase", new String[] {}),
            Map.entry("targetSelect", new String[] { "type", "parameters" }),
            Map.entry("targetFilePut", new String[] { "hostFile", "targetFile" }),
            Map.entry("targetFileGet", new String[] { "targetFile", "hostFile" }),
            Map.entry("targetFileDelete", new String[] { "targetFile" }),
            Map.entry("infoAdaExceptions", new String[] { "regexp" }),
            Map.entry("infoGdbMiCommand", new String[] { "commandName" }),
            Map.entry("listFeatures", new String[] {}),
            Map.entry("listTargetFeatures", new String[] {}),
            Map.entry("gdbExit", new String[] {}),
            Map.entry("gdbSet", new String[] { "variable", "value" }),
            Map.entry("gdbShow", new String[] { "variable" }),
            Map.entry("gdbVersion", new String[] {}),
            Map.entry("listThreadGroups", new String[] { "available", "recurse", "groups" }),
            Map.entry("infoOs", new String[] { "type" }),
            Map.entry("addInferior", new String[] { "noConnection" }),
            Map.entry("removeInferior", new String[] { "inferiorId" }),
            Map.entry("interpreterExec", new String[] { "interpreter", "command" }),
            Map.entry("setInferiorTty", new String[] { "tty" }),
            Map.entry("showInferiorTty", new String[] {}),
            Map.entry("enableTimings", new String[] { "enable" }),
            Map.entry("complete", new String[] { "command" }),
            Map.entry("exit", new String[] {}),
            Map.entry("send", new String[] { "cmd" }),
            Map.entry("setStopListener", new String[] { "l" }),
            Map.entry("setOutputListener", new String[] { "listener" }));

    // Map of method name to array indicating which parameters are required (true)
    // and which are optional (false)

    public static final Map<String, boolean[]> REQUIRED_PARAMS = Map.ofEntries(
            Map.entry("startEverything", new boolean[] { true, false }),
            Map.entry("startGdbServer", new boolean[] { true, false }),
            Map.entry("startGdb", new boolean[] {}),
            Map.entry("connectToServer", new boolean[] { false, false }),
            Map.entry("setBreakpoint", new boolean[] { true, false, false, false, false, false }),
            Map.entry("listBreakpoints", new boolean[] {}),
            Map.entry("deleteBreakpoints", new boolean[] { false }),
            Map.entry("disableBreakpoints", new boolean[] { false }),
            Map.entry("enableBreakpoints", new boolean[] { false }),
            Map.entry("breakpointInfo", new boolean[] { false }),
            Map.entry("breakAfter", new boolean[] { true, false }),
            Map.entry("setBreakpointCondition", new boolean[] { true, false }),
            Map.entry("setBreakpointConditionForced", new boolean[] { true, false }),
            Map.entry("setBreakpointCommands", new boolean[] { true, false }),
            Map.entry("dprintf", new boolean[] { true, true, false }),
            Map.entry("watch", new boolean[] { true, false }),
            Map.entry("setTracepointPasscount", new boolean[] { true, false }),
            Map.entry("setProgramArguments", new boolean[] { false }),
            Map.entry("changeDirectory", new boolean[] { true }),
            Map.entry("environmentDirectory", new boolean[] { false, false }),
            Map.entry("resetSourceDirectories", new boolean[] {}),
            Map.entry("resetAndAddSourceDirectories", new boolean[] { false }),
            Map.entry("showSourceDirectories", new boolean[] {}),
            Map.entry("environmentPath", new boolean[] { false, false }),
            Map.entry("showEnvironmentPath", new boolean[] {}),
            Map.entry("addEnvironmentPath", new boolean[] { false }),
            Map.entry("resetEnvironmentPath", new boolean[] {}),
            Map.entry("resetAndAddEnvironmentPath", new boolean[] { false }),
            Map.entry("printWorkingDirectory", new boolean[] {}),
            Map.entry("threadInfo", new boolean[] { false }),
            Map.entry("listThreadIds", new boolean[] {}),
            Map.entry("selectThread", new boolean[] { true }),
            Map.entry("adaTaskInfo", new boolean[] { false }),
            Map.entry("run", new boolean[] { false, false, false }),
            Map.entry("runAndStopAtMain", new boolean[] {}),
            Map.entry("runAll", new boolean[] {}),
            Map.entry("runThreadGroup", new boolean[] { true }),
            Map.entry("continueExec", new boolean[] { false, false, false }),
            Map.entry("continueThreadGroup", new boolean[] { true }),
            Map.entry("continueAll", new boolean[] {}),
            Map.entry("continueReverse", new boolean[] {}),
            Map.entry("interrupt", new boolean[] { false, false }),
            Map.entry("interruptAll", new boolean[] {}),
            Map.entry("interruptThreadGroup", new boolean[] { true }),
            Map.entry("next", new boolean[] { false }),
            Map.entry("nextReverse", new boolean[] {}),
            Map.entry("step", new boolean[] { false }),
            Map.entry("stepReverse", new boolean[] {}),
            Map.entry("until", new boolean[] { true }),
            Map.entry("nextInstruction", new boolean[] { false }),
            Map.entry("nextInstructionReverse", new boolean[] {}),
            Map.entry("stepInstruction", new boolean[] { false }),
            Map.entry("stepInstructionReverse", new boolean[] {}),
            Map.entry("finish", new boolean[] { false }),
            Map.entry("finishReverse", new boolean[] {}),
            Map.entry("returnFromFunction", new boolean[] {}),
            Map.entry("jump", new boolean[] { true }),
            Map.entry("enableFrameFilters", new boolean[] {}),
            Map.entry("stackInfoFrame", new boolean[] {}),
            Map.entry("stackInfoDepth", new boolean[] { false }),
            Map.entry("stackListFrames", new boolean[] { false, false, false }),
            Map.entry("stackListArguments", new boolean[] { false, false, false }),
            Map.entry("stackListLocals", new boolean[] { false, false, false }),
            Map.entry("stackListVariables", new boolean[] { false, false, false, false, false }),
            Map.entry("selectFrame", new boolean[] { true }),
            Map.entry("enablePrettyPrinting", new boolean[] {}),
            Map.entry("varCreate", new boolean[] { true, false }),
            Map.entry("varDelete", new boolean[] { true, false }),
            Map.entry("varSetFormat", new boolean[] { true, true }),
            Map.entry("varShowFormat", new boolean[] { true }),
            Map.entry("varInfoNumChildren", new boolean[] { true }),
            Map.entry("varListChildren", new boolean[] { true, false, false }),
            Map.entry("varInfoType", new boolean[] { true }),
            Map.entry("varInfoExpression", new boolean[] { true }),
            Map.entry("varInfoPathExpression", new boolean[] { true }),
            Map.entry("varShowAttributes", new boolean[] { true }),
            Map.entry("varEvaluate", new boolean[] { true, false }),
            Map.entry("varAssign", new boolean[] { true, true }),
            Map.entry("varUpdateAll", new boolean[] {}),
            Map.entry("varUpdate", new boolean[] { true }),
            Map.entry("varSetFrozen", new boolean[] { true, true }),
            Map.entry("varSetUpdateRange", new boolean[] { true, false, false }),
            Map.entry("varSetVisualizer", new boolean[] { true, true }),
            Map.entry("dataDisassembleRange", new boolean[] { true, true }),
            Map.entry("dataDisassembleFunction", new boolean[] { true }),
            Map.entry("dataDisassembleFileLine", new boolean[] { true, true }),
            Map.entry("dataDisassembleFileLineCount", new boolean[] { true, true, true }),
            Map.entry("dataDisassembleWithOpcodes", new boolean[] { true, true }),
            Map.entry("dataDisassembleWithSource", new boolean[] { true, true }),
            Map.entry("dataEvaluateExpression", new boolean[] { true }),
            Map.entry("dataListChangedRegisters", new boolean[] {}),
            Map.entry("dataListRegisterNames", new boolean[] { false }),
            Map.entry("dataListRegisterValues", new boolean[] { true, false }),
            Map.entry("dataReadMemoryBytes", new boolean[] { true, true }),
            Map.entry("dataReadMemoryBytesOffset", new boolean[] { true, true, true }),
            Map.entry("dataWriteMemoryBytes", new boolean[] { true, true, true }),
            Map.entry("traceFindNone", new boolean[] {}),
            Map.entry("traceFindFrameNumber", new boolean[] { true }),
            Map.entry("traceFindTracepointNumber", new boolean[] { true }),
            Map.entry("traceFindPc", new boolean[] { true }),
            Map.entry("traceFindPcInsideRange", new boolean[] { true, true }),
            Map.entry("traceFindPcOutsideRange", new boolean[] { true, true }),
            Map.entry("traceFindLine", new boolean[] { true }),
            Map.entry("traceDefineVariable", new boolean[] { true, true }),
            Map.entry("traceListVariables", new boolean[] {}),
            Map.entry("traceFrameCollected", new boolean[] {}),
            Map.entry("traceFrameCollectedVarPrint", new boolean[] { true }),
            Map.entry("traceFrameCollectedCompPrint", new boolean[] { true }),
            Map.entry("traceFrameCollectedRegisters", new boolean[] { true }),
            Map.entry("traceFrameCollectedMemoryContents", new boolean[] {}),
            Map.entry("traceFrameCollectedFull", new boolean[] { true, true, true }),
            Map.entry("traceStart", new boolean[] {}),
            Map.entry("traceStop", new boolean[] {}),
            Map.entry("traceStatus", new boolean[] {}),
            Map.entry("traceSave", new boolean[] { true, false, false }),
            Map.entry("symbolInfoFunctions", new boolean[] { false, false, false, false }),
            Map.entry("symbolInfoModuleFunctions", new boolean[] { true, false, false }),
            Map.entry("symbolInfoModuleVariables", new boolean[] { true, false, false }),
            Map.entry("symbolInfoModules", new boolean[] { false, false }),
            Map.entry("symbolInfoTypes", new boolean[] { false, false }),
            Map.entry("symbolInfoVariables", new boolean[] { false, false, false, false }),
            Map.entry("symbolListLines", new boolean[] { true }),
            Map.entry("fileExecAndSymbols", new boolean[] { true }),
            Map.entry("fileExecFile", new boolean[] { true }),
            Map.entry("fileListExecSourceFile", new boolean[] {}),
            Map.entry("fileListExecSourceFiles", new boolean[] { false }),
            Map.entry("fileListSharedLibraries", new boolean[] { false }),
            Map.entry("fileSymbolFile", new boolean[] { true }),
            Map.entry("targetAttach", new boolean[] { true }),
            Map.entry("targetDetach", new boolean[] { false }),
            Map.entry("targetDisconnect", new boolean[] {}),
            Map.entry("targetDownload", new boolean[] {}),
            Map.entry("targetFlashErase", new boolean[] {}),
            Map.entry("targetSelect", new boolean[] { true, true }),
            Map.entry("targetFilePut", new boolean[] { true, true }),
            Map.entry("targetFileGet", new boolean[] { true, true }),
            Map.entry("targetFileDelete", new boolean[] { true }),
            Map.entry("infoAdaExceptions", new boolean[] { false }),
            Map.entry("infoGdbMiCommand", new boolean[] { true }),
            Map.entry("listFeatures", new boolean[] {}),
            Map.entry("listTargetFeatures", new boolean[] {}),
            Map.entry("gdbExit", new boolean[] {}),
            Map.entry("gdbSet", new boolean[] { true, false }),
            Map.entry("gdbShow", new boolean[] { true }),
            Map.entry("gdbVersion", new boolean[] {}),
            Map.entry("listThreadGroups", new boolean[] { false, false, false }),
            Map.entry("infoOs", new boolean[] { false }),
            Map.entry("addInferior", new boolean[] { false }),
            Map.entry("removeInferior", new boolean[] { true }),
            Map.entry("interpreterExec", new boolean[] { true, true }),
            Map.entry("setInferiorTty", new boolean[] { true }),
            Map.entry("showInferiorTty", new boolean[] {}),
            Map.entry("enableTimings", new boolean[] { true }),
            Map.entry("complete", new boolean[] { true }),
            Map.entry("exit", new boolean[] {}),
            Map.entry("send", new boolean[] { true }),
            Map.entry("setStopListener", new boolean[] { true }),
            Map.entry("setOutputListener", new boolean[] { true }));

    // Array of common GDB commands for quick access used in the input provider

    public static final String[] COMMON_METHODS = new String[] {
            "step",
            "next",
            "continueAll",
            "setBreakpoint",
            "interrupt",
            "send",
            "exit"
    };
}
